"""
M1 verification: the FDM-shaped synthetic dataset actually satisfies
config/entities_fdm.yaml's required columns, and at least one bi-temporal
entity carries genuine multiple effective-dated versions per key -- not
just a current-state snapshot with an always-null EFFECTIVE_END_DT.

Run against data_generator/output_fdm/ (dev seed 42), generated by
data_generator/fdm/generate_fdm.py. If that directory doesn't exist yet,
these tests are skipped rather than failed, so a fresh checkout's default
`pytest tests/` doesn't require running the generator first.
"""

import os

import pandas as pd
import pytest
import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO_ROOT, "data_generator", "output_fdm")
CONTRACT_PATH = os.path.join(REPO_ROOT, "config", "entities_fdm.yaml")

pytestmark = pytest.mark.skipif(
    not os.path.isdir(OUT_DIR),
    reason="data_generator/output_fdm/ not generated -- run "
           "`python -m data_generator.fdm.generate_fdm` first",
)


def _load_contract():
    with open(CONTRACT_PATH) as f:
        return yaml.safe_load(f)


def _load_table_by_entity(entity_name: str) -> pd.DataFrame:
    """Resolves the physical file via the contract's own `domain` tag --
    {OUT_DIR}/{domain}/{physical_table}.csv -- the same resolution
    FdmLocalSource uses, so this test can't silently drift from the real
    read path."""
    spec = _load_contract()["entities"][entity_name]
    path = os.path.join(OUT_DIR, spec["domain"], f"{spec['physical_table']}.csv")
    return pd.read_csv(path)


@pytest.mark.parametrize("entity_name", [
    "PARTY", "PARTY_DEMOGRAPHIC", "PARTY_LOCATOR", "PARTY_AGREEMENT",
    "AGREEMENT", "AGREEMENT_DAILY_BALANCE", "MORTGAGE_AGREEMENT",
    "COLLATERAL_ITEM", "AGREEMENT_COLLATERAL_ITEM", "COLLATERAL_ITEM_VALUE",
    "EVENT_FINANCIAL",
])
def test_generated_table_has_required_columns(entity_name):
    contract = _load_contract()
    spec = contract["entities"][entity_name]
    df = _load_table_by_entity(entity_name)
    missing = set(spec["required_columns"]) - set(df.columns)
    assert not missing, f"{entity_name} missing required columns: {missing}"


def test_generated_table_row_counts_are_nonzero():
    contract = _load_contract()
    for entity_name in contract["entities"]:
        df = _load_table_by_entity(entity_name)
        assert len(df) > 0, f"{entity_name} generated zero rows"


def test_party_has_multiple_effective_dated_versions():
    """Confirms the bi-temporal generator actually produces history, not
    just current-state rows with a decorative EFFECTIVE_END_DT column --
    the exact failure mode docs/decision_record.md warns about."""
    party = _load_table_by_entity("PARTY")
    version_counts = party.groupby("PRTY_ID").size()
    assert (version_counts >= 2).any(), (
        "expected at least one PRTY_ID with 2+ effective-dated versions; "
        "got a flat current-state snapshot instead"
    )
    multi_version_id = version_counts[version_counts >= 2].index[0]
    versions = party[party["PRTY_ID"] == multi_version_id].sort_values("EFFECTIVE_START_DT")
    # every version except the last must have a non-null EFFECTIVE_END_DT
    assert versions["EFFECTIVE_END_DT"].iloc[:-1].notna().all()
    assert pd.isna(versions["EFFECTIVE_END_DT"].iloc[-1]) or versions["EFFECTIVE_END_DT"].iloc[-1] == ""


def test_collateral_item_value_has_multiple_effective_dated_versions():
    """This is this pass's substitute proof entity for bi-temporal
    correctness, since rating_downgrade (Risk domain) is out of scope --
    see config/entities_fdm.yaml's note on COLLATERAL_ITEM_VALUE."""
    values = _load_table_by_entity("COLLATERAL_ITEM_VALUE")
    version_counts = values.groupby("CLTRL_ITEM_ID").size()
    assert (version_counts >= 2).any(), (
        "expected at least one CLTRL_ITEM_ID with 2+ effective-dated "
        "valuations to prove collateral_coverage_drop can read history"
    )


def test_as_at_join_backbone_party_to_agreement_to_daily_balance():
    """Smoke-tests the exact FDM Join Backbone pattern from
    docs/decision_record.md: PARTY -> PARTY_AGREEMENT -> AGREEMENT ->
    AGREEMENT_DAILY_BALANCE, filtered to C&I segments, resolves to at
    least one row -- i.e. the join keys the generator wrote are actually
    consistent with each other, not just individually well-formed."""
    party = _load_table_by_entity("PARTY")
    party_agreement = _load_table_by_entity("PARTY_AGREEMENT")
    agreement = _load_table_by_entity("AGREEMENT")
    daily_balance = _load_table_by_entity("AGREEMENT_DAILY_BALANCE")

    current_party = party[party["EFFECTIVE_END_DT"].isna() | (party["EFFECTIVE_END_DT"] == "")]
    ci_party = current_party[current_party["PRTY_SGMNT_CD"].isin(["SME", "MID", "LRGE", "INST"])]

    joined = (
        ci_party.merge(party_agreement, on="PRTY_ID")
        .merge(agreement, on="AGRMNT_ID")
        .merge(daily_balance, on="AGRMNT_ID")
    )
    assert len(joined) > 0, "FDM join backbone produced zero rows -- broken key consistency"
