"""
Phase 5a schema onboarding -- generates a `config/entities_<name>.yaml`-shaped
contract from a profiler.TableProfile, entirely deterministic (no LLM):
grain (row count, informational), primary_key (from key_candidates),
required_columns (every profiled column, typed from the profiler's
inferred type), and a `provenance: profiled_from_user_schema` marker so
a generated contract is never confused with a hand-written one.

Writing the result to config/entities_<name>.yaml is a SEPARATE,
human-gated step (onboarding/accept.py) -- this module only builds the
in-memory dict/YAML text; it never touches config/ itself.
"""

from __future__ import annotations

import yaml

from onboarding.profiler import TableProfile

_TYPE_MAP = {"string": "string", "int": "int", "float": "decimal", "date": "date", "bool": "bool"}


def generate_contract(profiles: dict[str, TableProfile], schema_name: str) -> dict:
    entities = {}
    for physical_table, profile in profiles.items():
        required_columns = {
            c.name: {"type": _TYPE_MAP.get(c.inferred_type, "string"), "nullable": c.nullable}
            for c in profile.columns
        }
        entities[physical_table] = {
            "physical_table": physical_table,
            "grain": f"profiled: {profile.row_count} sampled rows",
            "primary_key": profile.key_candidates[:1] if profile.key_candidates else [],
            "required_columns": required_columns,
        }
    return {
        "contract_version": 1,
        "provenance": "profiled_from_user_schema",
        "entities": entities,
        "transformations": [],
    }


def contract_yaml_text(profiles: dict[str, TableProfile], schema_name: str) -> str:
    header = (
        f"# Auto-generated by onboarding/entity_contract_generator.py from a profile of\n"
        f"# the '{schema_name}' schema -- REVIEW before accepting. Every required_columns\n"
        f"# entry is a mechanical guess from sampled data (type inference, nullability,\n"
        f"# key-candidate detection), not a hand-verified contract. A human runs\n"
        f"# `python -m onboarding.accept {schema_name}` to register this for real.\n\n"
    )
    return header + yaml.safe_dump(generate_contract(profiles, schema_name), sort_keys=False, default_flow_style=False)
